name: pi-typesafe-router-repository
runtime:
  name: nodejs
  options:
    typescript: true
description: GitHub repository settings and main branch governance for pi-typesafe-router
backend:
  url: gs://tinydog-pulumi-state/pi-typesafe-router
